/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return service health. Always 200; ``status`` is ``degraded`` if the DB is down.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload
     * @description Detect each file's source, load its valid rows and report the rejected ones.
     */
    post: operations['upload_api_v1_ingestion_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Runs
     * @description Most recent ingestion runs first, each with a sample of its rejected rows.
     */
    get: operations['runs_api_v1_ingestion_runs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Status
     * @description Per-source coverage, missing sources and the as-of date.
     */
    get: operations['status_api_v1_ingestion_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Templates
     * @description Expected columns for every supported export, for the downloadable CSV templates.
     */
    get: operations['templates_api_v1_ingestion_templates_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Settings
     * @description The saved settings, or ``configured: false`` before the first save.
     */
    get: operations['get_settings_api_v1_settings_get']
    /**
     * Put Settings
     * @description Replace the settings; invalid values are rejected with a 422.
     */
    put: operations['put_settings_api_v1_settings_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/campaigns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Campaigns
     * @description Campaigns seen in uploaded data, for choosing which ones are protected.
     */
    get: operations['campaigns_api_v1_settings_campaigns_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Metrics
     * @description ``metric`` per day, per ``dimension`` value, compared with the period before.
     *
     *     ``end`` defaults to the as-of date.
     */
    get: operations['metrics_api_v1_metrics_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Today
     * @description Headline KPIs for the week to the as-of date vs the week before, with goal markers.
     */
    get: operations['today_api_v1_today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_upload_api_v1_ingestion_upload_post */
    Body_upload_api_v1_ingestion_upload_post: {
      /**
       * Files
       * @description One or more platform CSV exports
       */
      files: string[]
    }
    /** CampaignOut */
    CampaignOut: {
      /** Id */
      id: number
      /**
       * Channel Id
       * @enum {string}
       */
      channel_id: 'google_ads' | 'meta_ads'
      /** Name */
      name: string
    }
    /**
     * FestiveWindow
     * @description A sale or festival where big swings are expected, so signals are suppressed.
     */
    FestiveWindow: {
      /** Name */
      name: string
      /**
       * Start
       * Format: date
       */
      start: string
      /**
       * End
       * Format: date
       */
      end: string
    }
    /** GoalOut */
    GoalOut: {
      /** Target */
      target: number
      /**
       * Status
       * @enum {string}
       */
      status: 'ahead' | 'on_track' | 'behind'
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Reports overall status plus database and configured LLM provider.
     */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /**
       * Database
       * @enum {string}
       */
      database: 'ok' | 'unavailable'
      /** Llm Provider */
      llm_provider: string
    }
    /** IngestionRunOut */
    IngestionRunOut: {
      /** Id */
      id: number
      /** Source */
      source: ('google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders') | null
      /** File Name */
      file_name: string
      /**
       * Status
       * @enum {string}
       */
      status: 'success' | 'partial' | 'failed'
      /** Rows Total */
      rows_total: number
      /** Rows Accepted */
      rows_accepted: number
      /** Rows Rejected */
      rows_rejected: number
      /** Date From */
      date_from: string | null
      /** Date To */
      date_to: string | null
      /** Rejected Rows */
      rejected_rows: components['schemas']['RejectedRowOut'][]
      /** Error */
      error: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** IngestionStatusOut */
    IngestionStatusOut: {
      /** As Of Date */
      as_of_date: string | null
      /** Sources */
      sources: components['schemas']['SourceStatusOut'][]
      /** Missing Sources */
      missing_sources: ('google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders')[]
    }
    /** KpiSummaryOut */
    KpiSummaryOut: {
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'bounce_rate'
            | 'mer'
            | 'store_aov'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Value */
      value: number | null
      /** Previous */
      previous: number | null
      /** Change Pct */
      change_pct: number | null
      /** Higher Is Better */
      higher_is_better: boolean | null
      goal: components['schemas']['GoalOut'] | null
    }
    /** MetricSeriesOut */
    MetricSeriesOut: {
      /** Key */
      key: string
      /** Name */
      name: string
      /** Value */
      value: number | null
      /** Previous */
      previous: number | null
      /** Change Pct */
      change_pct: number | null
      /** Points */
      points: components['schemas']['SeriesPointOut'][]
    }
    /** MetricsOut */
    MetricsOut: {
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'bounce_rate'
            | 'mer'
            | 'store_aov'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Dimension */
      dimension: ('channel' | 'campaign' | 'ad_set' | 'creative' | 'age_group') | null
      period: components['schemas']['PeriodOut'] | null
      /** Series */
      series: components['schemas']['MetricSeriesOut'][]
    }
    /** PeriodOut */
    PeriodOut: {
      /**
       * Start
       * Format: date
       */
      start: string
      /**
       * End
       * Format: date
       */
      end: string
    }
    /** RejectedRowOut */
    RejectedRowOut: {
      /** Line */
      line: number
      /** Errors */
      errors: string[]
      /** Values */
      values: {
        [key: string]: string
      }
    }
    /** SeriesPointOut */
    SeriesPointOut: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Value */
      value: number | null
    }
    /** SettingsIn */
    SettingsIn: {
      /** Business Name */
      business_name: string
      /** Gross Margin Pct */
      gross_margin_pct: number
      /** Target Cpa */
      target_cpa?: number | null
      /** Target Roas */
      target_roas?: number | null
      /** Monthly Revenue Goal */
      monthly_revenue_goal?: number | null
      /** Monthly Budgets */
      monthly_budgets?: {
        [key: string]: number
      }
      /** Festive Windows */
      festive_windows?: components['schemas']['FestiveWindow'][]
      /** Protected Campaign Ids */
      protected_campaign_ids?: number[]
    }
    /**
     * SettingsOut
     * @description ``settings`` is null until the first save, which is what the first-run flow keys on.
     */
    SettingsOut: {
      /** Configured */
      configured: boolean
      settings: components['schemas']['SettingsIn'] | null
      /** Break Even Roas */
      break_even_roas: number | null
      /** Target Roas Profitable */
      target_roas_profitable: boolean | null
    }
    /** SourceStatusOut */
    SourceStatusOut: {
      /**
       * Source
       * @enum {string}
       */
      source: 'google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders'
      /** Label */
      label: string
      /** First Date */
      first_date: string | null
      /** Last Date */
      last_date: string | null
      /** Rows */
      rows: number
      /** Days */
      days: number
    }
    /** TemplateColumnOut */
    TemplateColumnOut: {
      /** Header */
      header: string
      /** Type */
      type: string
      /** Stored */
      stored: boolean
    }
    /** TemplateOut */
    TemplateOut: {
      /**
       * Source
       * @enum {string}
       */
      source: 'google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders'
      /** Label */
      label: string
      /** Columns */
      columns: components['schemas']['TemplateColumnOut'][]
      /** Csv Header */
      csv_header: string
    }
    /** TodayOut */
    TodayOut: {
      /** As Of Date */
      as_of_date: string | null
      /** Configured */
      configured: boolean
      period: components['schemas']['PeriodOut'] | null
      /** Kpis */
      kpis: components['schemas']['KpiSummaryOut'][]
      /** Trend */
      trend: components['schemas']['TrendPointOut'][]
    }
    /** TrendPointOut */
    TrendPointOut: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Store Revenue */
      store_revenue: number | null
      /** Spend */
      spend: number | null
      /** Roas */
      roas: number | null
      /** Mer */
      mer: number | null
      /** Cpa */
      cpa: number | null
    }
    /** UploadResponse */
    UploadResponse: {
      /** Runs */
      runs: components['schemas']['IngestionRunOut'][]
      status: components['schemas']['IngestionStatusOut']
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  upload_api_v1_ingestion_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_api_v1_ingestion_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  runs_api_v1_ingestion_runs_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionRunOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  status_api_v1_ingestion_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionStatusOut']
        }
      }
    }
  }
  templates_api_v1_ingestion_templates_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateOut'][]
        }
      }
    }
  }
  get_settings_api_v1_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingsOut']
        }
      }
    }
  }
  put_settings_api_v1_settings_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingsIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  campaigns_api_v1_settings_campaigns_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignOut'][]
        }
      }
    }
  }
  metrics_api_v1_metrics_get: {
    parameters: {
      query: {
        metric:
          | (
              | 'ctr'
              | 'cpc'
              | 'cpm'
              | 'cvr'
              | 'cpa'
              | 'roas'
              | 'aov'
              | 'frequency'
              | 'bounce_rate'
              | 'mer'
              | 'store_aov'
            )
          | (
              | 'impressions'
              | 'clicks'
              | 'spend'
              | 'platform_conversions'
              | 'platform_revenue'
              | 'store_revenue'
              | 'store_orders'
            )
        dimension?: ('channel' | 'campaign' | 'ad_set' | 'creative' | 'age_group') | null
        days?: number
        end?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MetricsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  today_api_v1_today_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TodayOut']
        }
      }
    }
  }
}
