/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return service health. Always 200; ``status`` is ``degraded`` if the DB is down.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload
     * @description Detect each file's source, load its valid rows and report the rejected ones.
     *
     *     New data means the signals are stale, so the analysis re-runs in the background.
     */
    post: operations['upload_api_v1_ingestion_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Runs
     * @description Most recent ingestion runs first, each with a sample of its rejected rows.
     */
    get: operations['runs_api_v1_ingestion_runs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Status
     * @description Per-source coverage, missing sources and the as-of date.
     */
    get: operations['status_api_v1_ingestion_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingestion/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Templates
     * @description Expected columns for every supported export, for the downloadable CSV templates.
     */
    get: operations['templates_api_v1_ingestion_templates_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analysis/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Status
     * @description Whether a run is in progress, and what the last one found.
     */
    get: operations['status_api_v1_analysis_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Settings
     * @description The saved settings, or ``configured: false`` before the first save.
     */
    get: operations['get_settings_api_v1_settings_get']
    /**
     * Put Settings
     * @description Replace the settings; invalid values are rejected with a 422.
     */
    put: operations['put_settings_api_v1_settings_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/campaigns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Campaigns
     * @description Campaigns seen in uploaded data, for choosing which ones are protected.
     */
    get: operations['campaigns_api_v1_settings_campaigns_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Metrics
     * @description ``metric`` per day, per ``dimension`` value, compared with the period before.
     *
     *     ``end`` defaults to the as-of date.
     */
    get: operations['metrics_api_v1_metrics_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/opportunities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Opportunities
     * @description Opportunities the last analysis found, most urgent first, filtered by status and kind.
     */
    get: operations['list_opportunities_api_v1_opportunities_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/opportunities/{opportunity_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Opportunity
     * @description One opportunity in four sections: what happened, the evidence, the likely cause
     *     and the recommended action, with the signals behind them.
     */
    get: operations['get_opportunity_api_v1_opportunities__opportunity_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/opportunities/{opportunity_id}/dismiss': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Dismiss Opportunity
     * @description Set an opportunity aside with a reason, so a re-run does not raise it again.
     */
    post: operations['dismiss_opportunity_api_v1_opportunities__opportunity_id__dismiss_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Today
     * @description Headline KPIs for the week to the as-of date vs the week before, with goal markers,
     *     plus the trust status of every source and month-to-date budget pacing.
     */
    get: operations['today_api_v1_today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/trust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Trust
     * @description Freshness of every source and, for ad channels, a tracking check against store orders.
     */
    get: operations['trust_api_v1_trust_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AnalysisStatusOut
     * @description The latest run, or an empty one before anything has been analysed.
     */
    AnalysisStatusOut: {
      /** Status */
      status: ('running' | 'done' | 'failed') | null
      /** As Of Date */
      as_of_date: string | null
      /** Signal Count */
      signal_count: number
      /** Opportunity Count */
      opportunity_count: number
      /** Started At */
      started_at: string | null
      /** Finished At */
      finished_at: string | null
      /** Error */
      error: string | null
    }
    /** Body_upload_api_v1_ingestion_upload_post */
    Body_upload_api_v1_ingestion_upload_post: {
      /**
       * Files
       * @description One or more platform CSV exports
       */
      files: string[]
    }
    /** CampaignOut */
    CampaignOut: {
      /** Id */
      id: number
      /**
       * Channel Id
       * @enum {string}
       */
      channel_id: 'google_ads' | 'meta_ads'
      /** Name */
      name: string
    }
    /** ChannelPacingOut */
    ChannelPacingOut: {
      /**
       * Channel
       * @enum {string}
       */
      channel: 'google_ads' | 'meta_ads'
      pacing: components['schemas']['PacingOut']
      /** Label */
      readonly label: string
    }
    /**
     * DismissIn
     * @description Why this is being set aside; it goes to the decision log.
     */
    DismissIn: {
      /** Reason */
      reason: string
    }
    /** EntityOut */
    EntityOut: {
      /** Level */
      level: string
      /** Key */
      key: string
      /** Name */
      name: string
      /** Channel */
      channel?: string | null
    }
    /**
     * FestiveWindow
     * @description A sale or festival where big swings are expected, so signals are suppressed.
     */
    FestiveWindow: {
      /** Name */
      name: string
      /**
       * Start
       * Format: date
       */
      start: string
      /**
       * End
       * Format: date
       */
      end: string
    }
    /** FreshnessOut */
    FreshnessOut: {
      /** Last Date */
      last_date: string | null
      /** Days Behind */
      days_behind: number
      /** Missing Dates */
      missing_dates: string[]
    }
    /** GoalOut */
    GoalOut: {
      /** Target */
      target: number
      /**
       * Status
       * @enum {string}
       */
      status: 'ahead' | 'on_track' | 'behind'
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Reports overall status plus database and configured LLM provider.
     */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /**
       * Database
       * @enum {string}
       */
      database: 'ok' | 'unavailable'
      /** Llm Provider */
      llm_provider: string
    }
    /** HypothesisOut */
    HypothesisOut: {
      /**
       * Cause
       * @enum {string}
       */
      cause:
        | 'creative_fatigue'
        | 'landing_page_break'
        | 'cpc_spike'
        | 'audience_mismatch'
        | 'tracking_break'
        | 'budget_overpace'
        | 'channel_opportunity'
        | 'conversion_drop'
        | 'unknown'
      /** Cause Label */
      cause_label: string
      /** Statement */
      statement: string
      /** Signal Ids */
      signal_ids: string[]
    }
    /** IngestionRunOut */
    IngestionRunOut: {
      /** Id */
      id: number
      /** Source */
      source: ('google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders') | null
      /** File Name */
      file_name: string
      /**
       * Status
       * @enum {string}
       */
      status: 'success' | 'partial' | 'failed'
      /** Rows Total */
      rows_total: number
      /** Rows Accepted */
      rows_accepted: number
      /** Rows Rejected */
      rows_rejected: number
      /** Date From */
      date_from: string | null
      /** Date To */
      date_to: string | null
      /** Rejected Rows */
      rejected_rows: components['schemas']['RejectedRowOut'][]
      /** Error */
      error: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** IngestionStatusOut */
    IngestionStatusOut: {
      /** As Of Date */
      as_of_date: string | null
      /** Sources */
      sources: components['schemas']['SourceStatusOut'][]
      /** Missing Sources */
      missing_sources: ('google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders')[]
    }
    /** KpiSummaryOut */
    KpiSummaryOut: {
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Value */
      value: number | null
      /** Previous */
      previous: number | null
      /** Change Pct */
      change_pct: number | null
      /** Higher Is Better */
      higher_is_better: boolean | null
      goal: components['schemas']['GoalOut'] | null
      /** Reliable */
      reliable: boolean
    }
    /** MetricSeriesOut */
    MetricSeriesOut: {
      /** Key */
      key: string
      /** Name */
      name: string
      /** Value */
      value: number | null
      /** Previous */
      previous: number | null
      /** Change Pct */
      change_pct: number | null
      /** Points */
      points: components['schemas']['SeriesPointOut'][]
    }
    /** MetricsOut */
    MetricsOut: {
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Dimension */
      dimension: ('channel' | 'campaign' | 'ad_set' | 'creative' | 'age_group') | null
      period: components['schemas']['PeriodOut'] | null
      /** Series */
      series: components['schemas']['MetricSeriesOut'][]
    }
    /**
     * NodeOut
     * @description One metric in the evidence tree, with its share of the change above it.
     */
    NodeOut: {
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Before */
      before: number | null
      /** After */
      after: number | null
      /** Change Pct */
      change_pct: number | null
      /** Share Pct */
      share_pct: number | null
      /** Higher Is Better */
      higher_is_better: boolean | null
      /**
       * Children
       * @default []
       */
      children: components['schemas']['NodeOut'][]
    }
    /**
     * OpportunityDetailOut
     * @description The four sections of UI.md §5.2, in that order, plus the signals behind them.
     */
    OpportunityDetailOut: {
      summary: components['schemas']['OpportunityOut']
      tree: components['schemas']['NodeOut'] | null
      /** Hypotheses */
      hypotheses: components['schemas']['HypothesisOut'][]
      /** Alternatives */
      alternatives: string[]
      recommendation: components['schemas']['RecommendationOut'] | null
      /** Signals */
      signals: components['schemas']['SignalOut'][]
      /**
       * Trust
       * @enum {string}
       */
      trust: 'ok' | 'warning' | 'broken'
      /** Protected */
      protected: boolean
      /** Grounded */
      grounded: boolean
    }
    /** OpportunityListOut */
    OpportunityListOut: {
      /** Opportunities */
      opportunities: components['schemas']['OpportunityOut'][]
    }
    /**
     * OpportunityOut
     * @description A list row: priority dot, title, channel, impact, confidence and age.
     */
    OpportunityOut: {
      /** Id */
      id: number
      /** Key */
      key: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'issue' | 'win'
      /**
       * Status
       * @enum {string}
       */
      status: 'open' | 'dismissed' | 'experimenting' | 'resolved'
      /** Title */
      title: string
      /** Entity Level */
      entity_level: string
      /** Entity Key */
      entity_key: string
      /** Entity Name */
      entity_name: string
      /** Channel Id */
      channel_id: string | null
      window: components['schemas']['PeriodOut']
      /**
       * First Seen
       * Format: date
       */
      first_seen: string
      /** Primary Metric */
      primary_metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Primary Detector */
      primary_detector: string
      /** Current */
      current: number | null
      /** Baseline */
      baseline: number | null
      /** Change Pct */
      change_pct: number | null
      /** Impact */
      impact: number
      /** Confidence */
      confidence: number | null
      /** Priority */
      priority: number | null
      /**
       * Band
       * @enum {string}
       */
      band: 'high' | 'medium' | 'low'
      /** Age Days */
      age_days: number
      /** Signal Count */
      signal_count: number
      /** Cause */
      cause:
        | (
            | 'creative_fatigue'
            | 'landing_page_break'
            | 'cpc_spike'
            | 'audience_mismatch'
            | 'tracking_break'
            | 'budget_overpace'
            | 'channel_opportunity'
            | 'conversion_drop'
            | 'unknown'
          )
        | null
      /** Cause Label */
      cause_label: string | null
      /** Observation */
      observation: string | null
      /** Diagnosis Source */
      diagnosis_source: ('llm' | 'rules') | null
      /** Dismissed Reason */
      dismissed_reason: string | null
    }
    /** PacingOut */
    PacingOut: {
      /** Budget */
      budget: number
      /** Spent */
      spent: number
      /** Spent Pct */
      spent_pct: number
      /** Remaining Budget */
      remaining_budget: number
      /** Month Elapsed Pct */
      month_elapsed_pct: number
      /** Projected */
      projected: number
      /**
       * Status
       * @enum {string}
       */
      status: 'on_track' | 'over' | 'under'
      /** Daily Run Rate */
      daily_run_rate: number
      /** Suggested Daily */
      suggested_daily: number | null
    }
    /** PacingViewOut */
    PacingViewOut: {
      month: components['schemas']['PeriodOut'] | null
      total: components['schemas']['PacingOut'] | null
      /** Channels */
      channels: components['schemas']['ChannelPacingOut'][]
    }
    /** PeriodOut */
    PeriodOut: {
      /**
       * Start
       * Format: date
       */
      start: string
      /**
       * End
       * Format: date
       */
      end: string
    }
    /** RecommendationOut */
    RecommendationOut: {
      /**
       * Action
       * @enum {string}
       */
      action:
        | 'pause_creative'
        | 'rotate_creative'
        | 'refine_audience'
        | 'investigate_landing_page'
        | 'fix_tracking'
        | 'shift_budget'
        | 'adjust_pacing'
      /** Rationale */
      rationale: string
      /** Expected Impact */
      expected_impact: [number, number]
      /** Confidence */
      confidence: number
      /**
       * Risk
       * @enum {string}
       */
      risk: 'low' | 'medium' | 'high'
      /** Watch */
      watch:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      /** Stop Condition */
      stop_condition: string
      /** Params */
      params: {
        [key: string]: string
      }
    }
    /** RejectedRowOut */
    RejectedRowOut: {
      /** Line */
      line: number
      /** Errors */
      errors: string[]
      /** Values */
      values: {
        [key: string]: string
      }
    }
    /** SeriesPointOut */
    SeriesPointOut: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Value */
      value: number | null
    }
    /** SettingsIn */
    SettingsIn: {
      /** Business Name */
      business_name: string
      /** Gross Margin Pct */
      gross_margin_pct: number
      /** Target Cpa */
      target_cpa?: number | null
      /** Target Roas */
      target_roas?: number | null
      /** Monthly Revenue Goal */
      monthly_revenue_goal?: number | null
      /** Monthly Budgets */
      monthly_budgets?: {
        [key: string]: number
      }
      /** Festive Windows */
      festive_windows?: components['schemas']['FestiveWindow'][]
      /** Protected Campaign Ids */
      protected_campaign_ids?: number[]
    }
    /**
     * SettingsOut
     * @description ``settings`` is null until the first save, which is what the first-run flow keys on.
     */
    SettingsOut: {
      /** Configured */
      configured: boolean
      settings: components['schemas']['SettingsIn'] | null
      /** Break Even Roas */
      break_even_roas: number | null
      /** Target Roas Profitable */
      target_roas_profitable: boolean | null
    }
    /**
     * SignalOut
     * @description One movement behind the opportunity, as the "Signals" section lists them.
     */
    SignalOut: {
      /** Id */
      id: string
      /** Detector */
      detector: string
      /** Metric */
      metric:
        | (
            | 'ctr'
            | 'cpc'
            | 'cpm'
            | 'cvr'
            | 'cpa'
            | 'roas'
            | 'aov'
            | 'frequency'
            | 'mer'
            | 'store_aov'
            | 'bounce_rate'
            | 'atc_rate'
            | 'checkout_rate'
            | 'purchase_rate'
            | 'web_cvr'
          )
        | (
            | 'impressions'
            | 'clicks'
            | 'spend'
            | 'platform_conversions'
            | 'platform_revenue'
            | 'store_revenue'
            | 'store_orders'
          )
      entity: components['schemas']['EntityOut']
      window: components['schemas']['PeriodOut']
      /** Current */
      current: number | null
      /** Baseline */
      baseline: number | null
      /** Change Pct */
      change_pct: number | null
      /** Adverse */
      adverse: boolean
      /** Impact */
      impact: number
      /** Score */
      score: number
    }
    /** SourceStatusOut */
    SourceStatusOut: {
      /**
       * Source
       * @enum {string}
       */
      source: 'google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders'
      /** Label */
      label: string
      /** First Date */
      first_date: string | null
      /** Last Date */
      last_date: string | null
      /** Rows */
      rows: number
      /** Days */
      days: number
    }
    /** SourceTrustOut */
    SourceTrustOut: {
      /**
       * Source
       * @enum {string}
       */
      source: 'google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders'
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'warning' | 'broken'
      freshness: components['schemas']['FreshnessOut']
      tracking: components['schemas']['TrackingOut'] | null
      /** Label */
      readonly label: string
    }
    /** TemplateColumnOut */
    TemplateColumnOut: {
      /** Header */
      header: string
      /** Type */
      type: string
      /** Stored */
      stored: boolean
    }
    /** TemplateOut */
    TemplateOut: {
      /**
       * Source
       * @enum {string}
       */
      source: 'google_ads' | 'meta_ads' | 'web_analytics' | 'store_orders'
      /** Label */
      label: string
      /** Columns */
      columns: components['schemas']['TemplateColumnOut'][]
      /** Csv Header */
      csv_header: string
    }
    /** TodayOut */
    TodayOut: {
      /** As Of Date */
      as_of_date: string | null
      /** Configured */
      configured: boolean
      period: components['schemas']['PeriodOut'] | null
      /** Kpis */
      kpis: components['schemas']['KpiSummaryOut'][]
      /** Trend */
      trend: components['schemas']['TrendPointOut'][]
      trust: components['schemas']['TrustOut']
      pacing: components['schemas']['PacingViewOut']
      /** Attention */
      attention: components['schemas']['OpportunityOut'][]
      /** Wins */
      wins: components['schemas']['OpportunityOut'][]
      /** Analysing */
      analysing: boolean
    }
    /** TrackingOut */
    TrackingOut: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'warning' | 'broken'
      /** Ratio Change */
      ratio_change: number
      /** Since */
      since: string | null
      /** Conversions Change Pct */
      conversions_change_pct: number | null
      /** Orders Change Pct */
      orders_change_pct: number | null
    }
    /** TrendPointOut */
    TrendPointOut: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Store Revenue */
      store_revenue: number | null
      /** Spend */
      spend: number | null
      /** Roas */
      roas: number | null
      /** Mer */
      mer: number | null
      /** Cpa */
      cpa: number | null
    }
    /** TrustOut */
    TrustOut: {
      /** As Of Date */
      as_of_date: string | null
      /** Sources */
      sources: components['schemas']['SourceTrustOut'][]
    }
    /** UploadResponse */
    UploadResponse: {
      /** Runs */
      runs: components['schemas']['IngestionRunOut'][]
      status: components['schemas']['IngestionStatusOut']
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  upload_api_v1_ingestion_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_api_v1_ingestion_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  runs_api_v1_ingestion_runs_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionRunOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  status_api_v1_ingestion_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionStatusOut']
        }
      }
    }
  }
  templates_api_v1_ingestion_templates_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateOut'][]
        }
      }
    }
  }
  status_api_v1_analysis_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnalysisStatusOut']
        }
      }
    }
  }
  get_settings_api_v1_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingsOut']
        }
      }
    }
  }
  put_settings_api_v1_settings_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingsIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  campaigns_api_v1_settings_campaigns_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignOut'][]
        }
      }
    }
  }
  metrics_api_v1_metrics_get: {
    parameters: {
      query: {
        metric:
          | (
              | 'ctr'
              | 'cpc'
              | 'cpm'
              | 'cvr'
              | 'cpa'
              | 'roas'
              | 'aov'
              | 'frequency'
              | 'mer'
              | 'store_aov'
              | 'bounce_rate'
              | 'atc_rate'
              | 'checkout_rate'
              | 'purchase_rate'
              | 'web_cvr'
            )
          | (
              | 'impressions'
              | 'clicks'
              | 'spend'
              | 'platform_conversions'
              | 'platform_revenue'
              | 'store_revenue'
              | 'store_orders'
            )
        dimension?: ('channel' | 'campaign' | 'ad_set' | 'creative' | 'age_group') | null
        days?: number
        end?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MetricsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_opportunities_api_v1_opportunities_get: {
    parameters: {
      query?: {
        status?: ('open' | 'dismissed' | 'experimenting' | 'resolved')[] | null
        kind?: ('issue' | 'win') | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpportunityListOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_opportunity_api_v1_opportunities__opportunity_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        opportunity_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpportunityDetailOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  dismiss_opportunity_api_v1_opportunities__opportunity_id__dismiss_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        opportunity_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DismissIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpportunityOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  today_api_v1_today_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TodayOut']
        }
      }
    }
  }
  trust_api_v1_trust_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TrustOut']
        }
      }
    }
  }
}
