"""ingestion tables

Revision ID: 5b94d3d5f003
Revises: 1afb142a9023
Create Date: 2026-09-28 17:17:19.177553

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b94d3d5f003"
down_revision: str | Sequence[str] | None = "1afb142a9023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_channel",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_channel")),
    )
    op.create_table(
        "fact_store_daily",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("orders", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discounts", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("refunds", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("new_customers", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_fact_store_daily")),
    )
    op.create_table(
        "fact_web_daily",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("device", sa.String(length=16), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("bounces", sa.Integer(), nullable=False),
        sa.Column("add_to_cart", sa.Integer(), nullable=False),
        sa.Column("checkout", sa.Integer(), nullable=False),
        sa.Column("purchases", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("date", "source", "device", name=op.f("pk_fact_web_daily")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rows_total", sa.Integer(), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("rejected_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('success', 'partial', 'failed')", name=op.f("ck_ingestion_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "dim_campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["dim_channel.id"], name=op.f("fk_dim_campaign_channel_id_dim_channel")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_campaign")),
        sa.UniqueConstraint(
            "channel_id", "external_id", name=op.f("uq_dim_campaign_channel_id_external_id")
        ),
    )
    op.create_table(
        "dim_ad_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["dim_campaign.id"],
            name=op.f("fk_dim_ad_set_campaign_id_dim_campaign"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_ad_set")),
        sa.UniqueConstraint(
            "campaign_id", "external_id", name=op.f("uq_dim_ad_set_campaign_id_external_id")
        ),
    )
    op.create_table(
        "dim_creative",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_set_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_set_id"], ["dim_ad_set.id"], name=op.f("fk_dim_creative_ad_set_id_dim_ad_set")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dim_creative")),
        sa.UniqueConstraint(
            "ad_set_id", "external_id", name=op.f("uq_dim_creative_ad_set_id_external_id")
        ),
    )
    op.create_table(
        "fact_ad_daily",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("creative_id", sa.Integer(), nullable=False),
        sa.Column("age_group", sa.String(length=16), nullable=False),
        sa.Column("device", sa.String(length=16), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("ad_set_id", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("platform_conversions", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("platform_revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_set_id"], ["dim_ad_set.id"], name=op.f("fk_fact_ad_daily_ad_set_id_dim_ad_set")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["dim_campaign.id"],
            name=op.f("fk_fact_ad_daily_campaign_id_dim_campaign"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["dim_channel.id"], name=op.f("fk_fact_ad_daily_channel_id_dim_channel")
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"],
            ["dim_creative.id"],
            name=op.f("fk_fact_ad_daily_creative_id_dim_creative"),
        ),
        sa.PrimaryKeyConstraint(
            "date", "creative_id", "age_group", "device", "region", name=op.f("pk_fact_ad_daily")
        ),
    )
    op.create_index(
        "ix_fact_ad_daily_campaign_date", "fact_ad_daily", ["campaign_id", "date"], unique=False
    )
    op.create_index(
        "ix_fact_ad_daily_channel_date", "fact_ad_daily", ["channel_id", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fact_ad_daily_channel_date", table_name="fact_ad_daily")
    op.drop_index("ix_fact_ad_daily_campaign_date", table_name="fact_ad_daily")
    op.drop_table("fact_ad_daily")
    op.drop_table("dim_creative")
    op.drop_table("dim_ad_set")
    op.drop_table("dim_campaign")
    op.drop_table("ingestion_runs")
    op.drop_table("fact_web_daily")
    op.drop_table("fact_store_daily")
    op.drop_table("dim_channel")
    # ### end Alembic commands ###
