"""settings table

Revision ID: ad100d2a30ba
Revises: 5b94d3d5f003
Create Date: 2026-09-28 18:10:14.391477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad100d2a30ba"
down_revision: str | Sequence[str] | None = "5b94d3d5f003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("business_name", sa.String(length=128), nullable=False),
        sa.Column("gross_margin_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("target_cpa", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("target_roas", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("monthly_revenue_goal", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monthly_budgets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("festive_windows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "protected_campaign_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
