"""SQLAlchemy declarative base.

All ORM models inherit from :class:`Base`. Kept import-light so Alembic can import
model metadata without pulling in the whole app.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint names keep autogenerated migrations stable and reversible.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all MDIA ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
